# Generated by Django 5.2.12 on 2026-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_address_customer_created_at_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
