# Generated by Django 5.2.10 on 2026-03-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('brand', models.CharField(max_length=100, verbose_name='Thương hiệu')),
                ('category', models.CharField(choices=[('shirt', 'Áo sơ mi'), ('tshirt', 'Áo thun'), ('pants', 'Quần dài'), ('shorts', 'Quần short'), ('dress', 'Đầm / Váy'), ('jacket', 'Áo khoác'), ('sportswear', 'Đồ thể thao'), ('underwear', 'Đồ lót'), ('accessory', 'Phụ kiện thời trang'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('freesize', 'Free Size')], default='M', max_length=10, verbose_name='Kích cỡ')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('unisex', 'Unisex'), ('kid', 'Trẻ em')], default='unisex', max_length=10, verbose_name='Giới tính')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Chất liệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá (VNĐ)')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm quần áo',
                'verbose_name_plural': 'Sản phẩm quần áo',
                'ordering': ['-created_at'],
            },
        ),
    ]
