# Generated by Django 5.2.10 on 2026-03-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('brand', models.CharField(max_length=100, verbose_name='Thương hiệu')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Mã model')),
                ('category', models.CharField(choices=[('phone', 'Điện thoại'), ('laptop', 'Laptop'), ('tablet', 'Máy tính bảng'), ('tv', 'Tivi'), ('audio', 'Âm thanh'), ('camera', 'Camera'), ('accessory', 'Phụ kiện'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá (VNĐ)')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Bảo hành (tháng)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm điện tử',
                'verbose_name_plural': 'Sản phẩm điện tử',
                'ordering': ['-created_at'],
            },
        ),
    ]
