# Generated by Django 5.2.12 on 2026-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
